# Generated by Django 3.1 on 2020-08-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(default='', upload_to='product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
