# Generated by Django 3.1 on 2020-08-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200806_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='icon',
        ),
    ]
