# Generated by Django 3.1 on 2020-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200806_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
