# Generated by Django 3.1 on 2020-08-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200806_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('page_accueil', models.BooleanField(default=False, verbose_name="Page d'accueil")),
                ('image', models.ImageField(upload_to='product/')),
                ('fiche', models.ImageField(upload_to='product/fiche/')),
                ('actif', models.BooleanField(default=True)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorie')),
            ],
        ),
    ]
