# Generated by Django 3.1 on 2020-08-09 09:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
