# Generated by Django 3.1 on 2020-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_produit_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='definition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
