# Generated by Django 3.1 on 2020-08-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_produit_definition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Categorie',
            new_name='categorie',
        ),
    ]
