# Generated by Django 3.1 on 2020-08-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='logo_noir',
        ),
    ]
