# Generated by Django 3.1 on 2020-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_reference_logo_noir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image4',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image5',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
