# Generated by Django 3.1 on 2020-08-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_produit_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image_test',
        ),
    ]
