# Generated by Django 3.1 on 2020-08-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_produit_image_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image3',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image4',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image5',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
