# Generated by Django 3.1 on 2020-09-03 11:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200827_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propos', models.CharField(choices=[('PP', 'À propos des produits'), ('SA', 'Service après-vente'), ('AU', "ÀÀ propos de l'usine - visite")], max_length=2)),
                ('question', models.CharField(max_length=200)),
                ('reponse', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
